/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Body: typeof import('./components/Body.vue')['default']
    Experiencias: typeof import('./components/Experiencias.vue')['default']
    Habilidades: typeof import('./components/Habilidades.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
